### ISSUE TITLE
Testing upload

### ISSUE THREAD

**Issue by znicholls** [znicholls/CMIP6-json-data-citation-generator#2]
@MartinaSt Do you want to include uploading in this repository? If yes, is there a way we can test that the upload works? The options I'm thinking of are:

- actually do an upload with a fake name, that you can easily find and delete/ignore?
- test that the json is the right format and test that the upload would be done, but don't actually do it?

**Comment by MartinaSt** [comment]
@znicholls Good question...

> Do you want to include uploading in this repository? If yes, is there a way we can test that the upload works? 

It is easy to update/overwrite but not easy to delete/ignore. Because of the authentication fakes would either need to be introduced for every citation manager (currently 50) or everybody uses a common fake identity and works on the same fake data. I don't think this is a good idea, might create confusion. Checking the json is only done at the start in the sense that the file is a valid json. Checking the content would be nice but there is currently no capacity to do it, not in the time frame we are talking about.

Thus, I would not do an automated upload of the created jsons, at least not by default. Users should try a single json file upload before doing multiple uploads automatically. What about implementing the upload part but deactivate it by default? Or do you have any better suggestion?

**Comment by znicholls** [comment]
> What about implementing the upload part but deactivate it by default?

I think this is the right approach. 

The last step of all of this can be making sure that the files I produce can actually be uploaded, we can talk about the best way for me to do that later.

**Comment by znicholls** [comment]
Closed by #4
